apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton101lab-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/IBM/tekton-tutorial-openshift.git
    - name: gitRevision
      value: master
    - name: pathToYamlFile
      value: "kubernetes/picalc.yaml"
    - name: imageUrl
      value: <REGISTRY>/<NAMESPACE>/picalc
    - name: imageTag
      value: <NAME>-v1
  serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: picalc-source-pvc